from enum import StrEnum


class ErrorResponseErrorCode(StrEnum):
    ALREADY_CLASSIFIED = "already_classified"
    ALREADY_MEMBER = "already_member"
    BILLING_NOT_CONFIGURED = "billing_not_configured"
    CHANNEL_DISABLED = "channel_disabled"
    CLASSIFICATION_PENDING = "classification_pending"
    CONFIRMATION_RATE_LIMITED = "confirmation_rate_limited"
    CONFIRMATION_REQUIRES_RESEND = "confirmation_requires_resend"
    CONFLICT = "conflict"
    DATABASE_NOT_READY = "database_not_ready"
    DATABASE_UNAVAILABLE = "database_unavailable"
    DEFAULT_GROUP = "default_group"
    DEFAULT_GROUP_CONTEXT = "default_group_context"
    DELIVERY_KEY_UNAVAILABLE = "delivery_key_unavailable"
    DELIVERY_NOT_CONFIGURED = "delivery_not_configured"
    DELIVERY_REQUEST_INCOMPLETE = "delivery_request_incomplete"
    DIGEST_HAS_REPLAY = "digest_has_replay"
    DIGEST_RETRY_EXPIRED = "digest_retry_expired"
    DUPLICATE_GROUP = "duplicate_group"
    DUPLICATE_KEYWORD = "duplicate_keyword"
    DUPLICATE_SEGMENT = "duplicate_segment"
    DUPLICATE_VIEW = "duplicate_view"
    EMAIL_HOURLY_LIMIT = "email_hourly_limit"
    EMAIL_IDEMPOTENCY_EXPIRED = "email_idempotency_expired"
    EMAIL_NOT_CONFIGURED = "email_not_configured"
    EMAIL_TEST_RATE_LIMITED = "email_test_rate_limited"
    EMAIL_TRANSPORT_UNAVAILABLE = "email_transport_unavailable"
    FORBIDDEN = "forbidden"
    HOURLY_EMAIL_UNSUPPORTED = "hourly_email_unsupported"
    INSUFFICIENT_BALANCE = "insufficient_balance"
    INTERNAL_ERROR = "internal_error"
    INVALID_ASSIGNEE = "invalid_assignee"
    INVALID_CURSOR = "invalid_cursor"
    INVALID_HOST = "invalid_host"
    INVALID_ORIGIN = "invalid_origin"
    INVALID_SIGNATURE = "invalid_signature"
    INVALID_TOKEN = "invalid_token"
    KEYWORD_INACTIVE = "keyword_inactive"
    KEYWORD_LIMIT_REACHED = "keyword_limit_reached"
    KEY_LIMIT = "key_limit"
    LAST_OWNER = "last_owner"
    NOT_A_DIGEST = "not_a_digest"
    NOT_CONFIGURED = "not_configured"
    NOT_FOUND = "not_found"
    NOT_REPLAYABLE = "not_replayable"
    NOT_RETRYABLE = "not_retryable"
    NO_BILLING_OWNER = "no_billing_owner"
    NO_CHANNELS = "no_channels"
    NO_RECIPIENTS = "no_recipients"
    PAYLOAD_TOO_LARGE = "payload_too_large"
    RATE_LIMITED = "rate_limited"
    READ_ONLY_KEY = "read_only_key"
    RECIPIENT_SUPPRESSED = "recipient_suppressed"
    REQUEST_CONFLICT = "request_conflict"
    REQUEST_TIMEOUT = "request_timeout"
    RULE_DISABLED = "rule_disabled"
    SLACK_NOT_CONFIGURED = "slack_not_configured"
    SLACK_NOT_CONNECTED = "slack_not_connected"
    SOURCE_TIMEOUT = "source_timeout"
    SOURCE_UNAVAILABLE = "source_unavailable"
    STALE_VERSION = "stale_version"
    TELEGRAM_NOT_CONFIGURED = "telegram_not_configured"
    UNAUTHORIZED = "unauthorized"
    UNKNOWN_CHANNEL = "unknown_channel"
    UNSUPPORTED_MEDIA_TYPE = "unsupported_media_type"
    UPSTREAM_UNAVAILABLE = "upstream_unavailable"
    VALIDATION_ERROR = "validation_error"
    VERSION_CONFLICT = "version_conflict"

    def __str__(self) -> str:
        return str(self.value)
